### PR TITLE
H3 develop: build fixes for Solaris

### PR DESCRIPTION
**Pull request by sjaenick**
Fix Solaris build

### CODE REVIEW

**Comment by cryptogenomicon** [comment]
Hi Sebastien,

Looks good. I'd like to pull this in. A question and an issue first...

This is for Intel Solaris, right? We don't yet support SPARC Solaris in HMMER3, because we still need to port to SPARC VIS SIMD instructions.

Can you find an implementation of strsep() that's got a BSD-compatible license? We will be switching to the BSD license soon, which means we can't incorporate any third-party GPL code. Also, we need to retain copyright/license info on code fragments that we include, so please include that in the comment header for the function.

Thanks!
Sean

**Comment by sjaenick** [comment]
Hi Sean,

Intel Solaris, yes. I guess the user base for SPARC isn't large enough to even consider maintaining a port (especially given big endian and VIS SIMD).

I'll update this with a FreeBSD-based strsep() and some infrastructure to ease future compatibility with non-Linux OSs.

- Sebastian

**Comment by sjaenick** [comment]
Sean,

feel free to merge; I also opened a pull request for easel with some minor changes.

Sebastian

**Comment by cryptogenomicon** [comment]
Hi Sebastien,

Excellent, thanks for this. I've merged it in, but also made some revisions. I moved `strsep()` into our Easel library and handle it the way we handle similar portability issues; and removed `src/compat` as a result. I think it's fine for `${LIBS}` to include `-lsocket` and `-lnsl` even for non-network programs, so I removed NETPROGS and SOCKETLIBS from configure.ac and Makefile.in to simplify.

I don't have a Solaris machine to test on, so you'll want to verify that I haven't messed up your port by doing this!

**Pull request merged**
