### PR TITLE
Fix alimask out-of-range errors (iss #237)

### PR DESCRIPTION
**Pull request by traviswheeler**
This commit addresses issue #237:

"Alimask crashes if asked to mask an alignment in a region that's outside the range of the alignment."

I've added range checks on all four of --alirange, --modelrange, --ali2model, and --model2ali. For all four:
- the smallest among all `<from>` positions must be >0
- for all ranges, `<to>` can not be less that `<from>`
- the largest among `<to>` positions is restricted as is described in the next paragraphs.

For (--alirange, --ali2model): `<to>` can not exceed the alignment length.

For (--modelrange, --model2ali):
- alimask works as before, computing the model that would be produced by hmmbuild (by numerous flags mirroring those from hmmbuild).
- for all ranges, `<to>` can not exceed the resulting model length.

The --ali2model required a bit of extra attention:
The purpose of this flag is to print, for each alignment range `<from>..<to>`, a mapping of the range with two pairs i..j => m..n,
such that
- i<=j
- i is the first alignment position between `<from>` and `<to>` (inclusive) that maps to a model position; that position is m
- j is the final alignment position between `<from>` and `<to>` (inclusive) that maps to a model position; that position is n

There were two bugs in this code. The first allowed j to exceed `<to>` if the `<to>` column did not map to a model position. This is fixed. The second allowed a range-pair i..j => m..n to be produced even if no alignment columns in the range `<from>..<to>` map to a model position. I've revised the mask output to indicate this lack of mapped positions with an output like:
          `<from>..<to>       ->       -..-  (no map)`

### CODE REVIEW

**Comment by cryptogenomicon** [comment]
Sounds good. @npcarter, could you have a look at this?

**Comment by npcarter** [comment]
Testing results: for all of --alirange, --modelrange, --ali2model, --model2ali, bounds checking works correctly.

--ali2model and --model2ali just output the conversions of the specified range to/from model space and did not generate an output msa file.  Is this the correct behavior?

Valgrind reports memory leaks when run with any of the --alirange --modelrange --model2ali, --ali2model flags.

**Comment by traviswheeler** [comment]
The --ali2model and --model2ali behavior is expected. I'll look into the valgrind errors.

**Comment by traviswheeler** [comment]
@npcarter: This should be good for another check. I've cleaned out the memory errors (allocated vars not free'd at exit) and made a few small tweaks to the help text.

**Comment by npcarter** [comment]
Every test of this version fails with the following error:

[npcarter@eddyfs01 hmmer]$ src/alimask --alirange 0-20 ../sequence_dbs/test.msa ~/foo.out
no such option --apendmask

**Comment by traviswheeler** [comment]
Sorry - the final changes I made (to account for re-spelling the appendmask flag) were sitting in a commit that I didn’t notice had failed.  I’ve pushed them now.

**Comment by npcarter** [comment]
This version looks good to go.  I've merged it into develop.

**Pull request merged**
