### PR TITLE
Add platform-specific implementation for ARM using NEON

### PR DESCRIPTION
**Pull request by althonos**
Supersedes #230, rebased to `h3-arm`.

You'll need `easel` checked out on the `master` branch to build. Compiles and passes all tests on my Raspberry Pi 4.

### CODE REVIEW

**Review by npcarter — APPROVED** [review]

**Comment by npcarter** [comment]
Pull request looks very good, only saw a few minor issues that I'll address.  Nice job!

**Comment by althonos** [comment]
Thanks! Sorry about the few whitespaces trimmed here and there, I had my editor setup with line trimming... I rolled back the files that had the most meaningless changes, but there are definitely some left in the diff!

**Comment by althonos** [comment]
Amazing, thanks!

**Comment by boegel** [comment]
Is there an ETA for an HMMER3 release that includes these changes?

**Comment by martin-g** [comment]
Would it be a good idea to enable TravisCI to run the build and tests on ARM64 ?
I would be happy to send a PR for this!
I see there is https://github.com/EddyRivasLab/hmmer/blob/master/.travis.yml but it seems it is not enabled at TravisCI (https://app.travis-ci.com/github/EddyRivasLab/hmmer) even for x86_64 at the moment.

**Comment by cryptogenomicon** [comment]
Thanks, but since we have a system for testing already, we haven't found TravisCI to be worth the extra effort.

**Comment by martin-g** [comment]
Thank you for your response, @cryptogenomicon !

> since we have a system for testing already

I knew it there must be something else! Does this system also have a builder on ARM64 ?

**Comment by cryptogenomicon** [comment]
Sorry, I don't know what you mean by "this system" or "a builder".

Our `make check` should run on any platform we support, including ARM64 platforms for the ARM dev branch.

**Comment by martin-g** [comment]
Because we were talking about TravisCI I thought that by "we have a system for testing already" you mean a CI running on internal machine(s), e.g. Jenkins/Buildbot/....
By "builder" I meant a CI agent running on Linux ARM64.

**Comment by cryptogenomicon** [comment]
We don't use CI. It seems like too much additional overhead for the scale of our project.

**Pull request merged**
