### PR TITLE
Correct clamp implementation in p7_oprofile.c.

### PR DESCRIPTION
**Pull request by Augustin-Zidek**

### CODE REVIEW

**Comment by cryptogenomicon** [comment]
Original code appears to be correct. Can you explain why you think there's something that needs fixing here?

**Comment by Augustin-Zidek** [comment]
This is just to remove a warning that we are possibly assigning an integer into a `uint8_t` which this code triggered. The reason is that the `uint8_t` case applies only to `cs`, not to the whole sum. As in #185, this bug was spotted by our automatic tools.

**Comment by cryptogenomicon** [comment]
I recall that that code is sensitive to order of evaluation, and that I've carefully checked it in the past. The assignment of a rounded float to `uint8_t` is unavoidable, inherent in the logic of what we're doing here. I'm loathe to change this code without a detailed reanalysis. If it's just to silence an overzealous tool warning, I'd rather close the PR.

**Comment by Augustin-Zidek** [comment]
I think it should be safe, for instance see the comparison of the generated assembly here: https://godbolt.org/z/eHEfBU (top: before this PR, bottom: after this PR - the assembly is the same in both cases). 

However, if you feel this poses an unnecessary risk, feel free to close this PR.

**Comment by cryptogenomicon** [comment]
Thanks. I'll close the PR.

**Pull request closed without merging**
