### PR TITLE
Arm

### PR DESCRIPTION
**Pull request by stationarysalesman**
ARM version of HMMER 4 that passes all the unit tests

### CODE REVIEW

**Comment by stationarysalesman** [comment]
Also, can we create an arm branch on the easel repo so I can make the pull request into the easel library?

**Comment by cryptogenomicon** [comment]
I don't think we need it, do we? I can accept a pull request into the develop branch, and it'll come in as one unit with all your commits/logs. 

Or do you want to keep it as a feature branch for now, but have it hosted on the github origin, not just on your local machine?

**Comment by stationarysalesman** [comment]
That's actually a better idea. As soon as I've surrounded the ARM NEON stuff with IFDEFS so that it builds on both machines I'll make the pull request.

**Comment by cryptogenomicon** [comment]
Done, thanks. 
A note for posterity's sake: I did pull this into our `arm` feature branch, not into `develop`. I had originally misunderstood what stage this code was at; I thought it was both Intel and ARM together (in which case it could be pulled into `develop`) but it's not, it's currently only intended to build on ARM. Getting our Intel and ARM implementations to play together will come later, in a merge of the `arm` branch to `develop`, likely involving a bunch of renaming of functions/files to `_sse`, `_neon`.

**Pull request merged**
